name: Deploy GitHub Pages with Jekyll to Main

on:
  push:
    branches:
      - main 

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: |
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to Main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy site to main"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
