name: Sync Main to Gh-pages

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Force push main to gh-pages
        run: |
          git checkout main
          git push origin main:gh-pages --force  # 强制将 main 推送到 gh-pages 分支
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
