name: Auto Force Merge Main to Gh-pages

on:
  push:
    branches:
      - main  

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main  

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages  
          git merge main --allow-unrelated-histories --no-ff --no-edit  

      - name: Force push changes to gh-pages
        run: |
          git push --force origin gh-pages  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
