name: Sync Main to Gh-pages

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Force push main to gh-pages
        run: |
          git checkout main
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jajamoa/sidpac-llm-sig.git main:gh-pages --force
